### ISSUE TITLE
How did you get pre-trained model on Dark Face dataset ?

### ISSUE THREAD

**Issue by Qidian213** [soumik12345/Zero-DCE#1]
Thanks!

**Comment by soumik12345** [comment]
I am not entirely sure what you mean by "pre-trained model on Dark Face dataset", but there is no such step involved in [Zero-DCE](https://www.arxiv-vanity.com/papers/2001.06826/). As for the model I have trained, you can find it [here](https://github.com/soumik12345/Zero-DCE/tree/master/pretrained-models).
